### ISSUE TITLE
Constant.php file is missing

### ISSUE THREAD

**Issue by rajnishbaldha** [bewithdhanu/codeigniter-3.2.1-with-admin-LTE-Template-Intigration#3]
Constant used in the php files like ROLE_ADMIN are not defined.

**Comment by bewithdhanu** [comment]
I have updated that code again with those constants and some other changes, please find those by pull new code

**Comment by bewithdhanu** [comment]
Thank You

**Comment by softydeveloper** [comment]
:) can i get the list of the features you added this time?

**Comment by bewithdhanu** [comment]
@softydeveloper, nop, just added label :-)
