### ISSUE TITLE
Unable to connect to your database server

### ISSUE THREAD

**Issue by consule** [bewithdhanu/codeigniter-3.2.1-with-admin-LTE-Template-Intigration#9]
I Got this error:

A Database Error Occurred
Unable to connect to your database server using the provided settings.

Filename: C:/xampp/htdocs/crm2/system/database/DB_driver.php

Line Number: 436

**Comment by bewithdhanu** [comment]
check your database credentials, and also check whether you started MySQL or not?

**Comment by consule** [comment]
Sorry, was it!
